list1 = ['Сергій', 'Вікторія']
print(list1)
print('Елемент 1: ', list1[0])
print('Елемент 2: ', list1[1])
list1[1] = 'Вікусічка'
print(list1)
print('Елемент 1: ', list1[0])
print('Елемент 2: ', list1[1])
list1.append('Юрій')
print(list1)
print('Елемент 1: ', list1[0])
print('Елемент 2: ', list1[1])
print('Елемент 3: ', list1[2])
list1.insert(1, 40)
list1.insert(3, 36)
list1.insert(5, 10)
print(list1)
list2 = ['тато', 'мамо', 'син']
print(list2)
print("extend:")
list1.extend(list2)
print(list1)
list1.remove('тато')
print(list1)
list1.pop()
print(list1)
list1.pop(1)
print(list1)
print(list2)
del list2
