# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(557, 673)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(80, 100, 201, 41))
        self.spinBox.setMaximum(1000)
        self.spinBox.setProperty("value", 100)
        self.spinBox.setObjectName("spinBox")
        self.spinBox_2 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_2.setGeometry(QtCore.QRect(80, 280, 201, 41))
        self.spinBox_2.setMinimum(1)
        self.spinBox_2.setMaximum(10)
        self.spinBox_2.setObjectName("spinBox_2")
        self.spinBox_3 = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_3.setGeometry(QtCore.QRect(80, 190, 201, 41))
        self.spinBox_3.setMaximum(1000)
        self.spinBox_3.setProperty("value", 100)
        self.spinBox_3.setObjectName("spinBox_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(80, 370, 201, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(80, 450, 201, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 540, 201, 51))
        self.pushButton.setObjectName("pushButton")
        self.label_v_color = QtWidgets.QLabel(self.centralwidget)
        self.label_v_color.setGeometry(QtCore.QRect(80, 420, 131, 21))
        self.label_v_color.setObjectName("label_v_color")
        self.label_i_color = QtWidgets.QLabel(self.centralwidget)
        self.label_i_color.setGeometry(QtCore.QRect(80, 330, 131, 21))
        self.label_i_color.setObjectName("label_i_color")
        self.label_y = QtWidgets.QLabel(self.centralwidget)
        self.label_y.setGeometry(QtCore.QRect(80, 150, 131, 21))
        self.label_y.setObjectName("label_y")
        self.label_scale = QtWidgets.QLabel(self.centralwidget)
        self.label_scale.setGeometry(QtCore.QRect(80, 250, 131, 21))
        self.label_scale.setObjectName("label_scale")
        self.label_x = QtWidgets.QLabel(self.centralwidget)
        self.label_x.setGeometry(QtCore.QRect(80, 60, 131, 21))
        self.label_x.setObjectName("label_x")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Панель керування"))
        self.lineEdit.setText(_translate("MainWindow", "green"))
        self.lineEdit_2.setText(_translate("MainWindow", "red"))
        self.pushButton.setText(_translate("MainWindow", "Змінити колір"))
        self.label_v_color.setText(_translate("MainWindow", "Колір не видимих ліній"))
        self.label_i_color.setText(_translate("MainWindow", "Колір видимих ліній"))
        self.label_y.setText(_translate("MainWindow", "Початкова У"))
        self.label_scale.setText(_translate("MainWindow", "Масштаб"))
        self.label_x.setText(_translate("MainWindow", "Початкова Х"))
